<?php

namespace App\Models\CarriersModel;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class CarrierCompanySnapshot extends Model
{
    protected $fillable = [
        'carrier_id',
        'row_id',
        'carrier_operation_desc',
        'authority_common',
        'property',
        'passenger',
        'household_goods',
        'household',
        'cargo_carried',
        'beverages',
        'building_materials',
        'chemicals',
        'coal_coke',
        'construction',
        'dry_bulk_commodities',
        'farm_supplies',
        'fresh_produce',
        'garbage_refuse_trash',
        'general_freight',
        'grain_feed_hay',
        'intermodal_containers',
        'liquids_gases',
        'livestock',
        'logs_poles_beams_lumber',
        'machinery_large_objects',
        'meat',
        'metal_sheet_coils_rolls',
        'mobile_homes',
        'motor_vehicles',
        'oilfield_equipment',
        'other_cargo',
        'paper_products',
        'passengers',
        'refrigerated_foods',
        'us_mail',
        'water_well',
        'operation_classification_desc',
        'operation_class_authorized_for_hire',
        'operation_class_exempt_for_hire',
        'operation_class_private_property',
        'operation_class_private_pass_business',
        'operation_class_private_pass_non_business',
        'operation_class_migrant',
        'operation_class_us_mail',
        'operation_class_federal_govt',
        'operation_class_state_govt',
        'operation_class_local_govt',
        'operation_class_indian_nation',
        'authority_start_contract',
        'authority_start_broker',
        'authority_common_last_revocation_date',
        'authority_contract_last_revocation_date',
        'authority_broker_last_revocation_date',
    ];

    protected $casts = [
        'property' => 'boolean',
        'passenger' => 'boolean',
        'household_goods' => 'boolean',
        'household' => 'boolean',
        'beverages' => 'boolean',
        'building_materials' => 'boolean',
        'chemicals' => 'boolean',
        'coal_coke' => 'boolean',
        'construction' => 'boolean',
        'dry_bulk_commodities' => 'boolean',
        'farm_supplies' => 'boolean',
        'fresh_produce' => 'boolean',
        'garbage_refuse_trash' => 'boolean',
        'general_freight' => 'boolean',
        'grain_feed_hay' => 'boolean',
        'intermodal_containers' => 'boolean',
        'liquids_gases' => 'boolean',
        'livestock' => 'boolean',
        'logs_poles_beams_lumber' => 'boolean',
        'machinery_large_objects' => 'boolean',
        'meat' => 'boolean',
        'metal_sheet_coils_rolls' => 'boolean',
        'mobile_homes' => 'boolean',
        'motor_vehicles' => 'boolean',
        'oilfield_equipment' => 'boolean',
        'other_cargo' => 'boolean',
        'paper_products' => 'boolean',
        'passengers' => 'boolean',
        'refrigerated_foods' => 'boolean',
        'us_mail' => 'boolean',
        'water_well' => 'boolean',
        'operation_class_authorized_for_hire' => 'boolean',
        'operation_class_exempt_for_hire' => 'boolean',
        'operation_class_private_property' => 'boolean',
        'operation_class_private_pass_business' => 'boolean',
        'operation_class_private_pass_non_business' => 'boolean',
        'operation_class_migrant' => 'boolean',
        'operation_class_us_mail' => 'boolean',
        'operation_class_federal_govt' => 'boolean',
        'operation_class_state_govt' => 'boolean',
        'operation_class_local_govt' => 'boolean',
        'operation_class_indian_nation' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    public function carrier(): BelongsTo
    {
        return $this->belongsTo(Carrier::class, 'carrier_id', 'id');
    }
}
